### ISSUE TITLE
Replace cub-hip with rocprim

### ISSUE THREAD

**Issue by petrex** [ROCmSoftwarePlatform/rocm-caffe2#78]
We need to replace cub-hip with RocM official parallel primitive --> rocPRIM.

The pre-release can be found here:

Code: https://github.com/ROCmSoftwarePlatform/rocPRIM/tree/milestone3_prerelease
Release: https://github.com/ROCmSoftwarePlatform/rocPRIM/releases/tag/v0.2.1

**Comment by oscarbg** [comment]
Hi just exploring this port and found new Project rocPRIM..
seems interestingly replaces cub-hip..
can't find anything under https://github.com/ROCmSoftwarePlatform/rocPRIM?
returns error no existant Project..
is for AMD internal use? any ETA on public Access?
thanks..

**Comment by VincentSC** [comment]
@oscarbg It's now public

**Comment by oscarbg** [comment]
Thanks @VincentSC  I downloaded days ago the preview.. still not tested tough on a Vega 56 on the TODO list.. :-(

**Comment by petrex** [comment]
WIP. #114

**Comment by VincentSC** [comment]
FYI: we released another dev-branch https://github.com/ROCmSoftwarePlatform/rocPRIM/tree/v0.3.2
Final version v1.0 is expected on Friday.

**Comment by petrex** [comment]
@VincentSC Do you guys have a plan to make rocprim self-contained?

**Comment by VincentSC** [comment]
Not sure if I follow you. Can you elaborate?

**Comment by petrex** [comment]
https://github.com/pytorch/pytorch
